[global]
padding = ""

[prompt]
string = " ‚ùØ "
foreground = "green"
error_foreground = "red"

[execution_time]
display_from = 2.0

[exit_status]
non_zero_only = true

[[module]]
name = "directory"
inner_prefix = "üñø  "
foreground = "blue"
bold = true

[[module]]
name = "git_branch"
inner_prefix = "ÓÇ† "
outer_prefix = " "
foreground = "green"

[[module]]
name = "git_status"
outer_prefix = " "
foreground = "green"

[[module]]
name = "execution_time"
inner_prefix = "‚åõÔ∏é"
outer_prefix = " "
foreground = "yellow"

[[module]]
name = "exit_status"
inner_prefix = "‚ö† "
outer_prefix = " "
foreground = "red"
