[global]
new_line = true

[prompt]
string = "\n❯ "
foreground = "green"
error_foreground = "red"

[execution_time]
display_from = 2.0

[exit_status]
non_zero_only = true

[[module]]
name = "directory"
align = "left"
outer_suffix = ""
background = "blue"
foreground = "black"

[[module]]
name = "separator"
background = "default"
outer_suffix = ""

[[module]]
name = "git_branch"
inner_prefix = "  "
background = "green"
foreground = "black"
padding = ""

[[module]]
name = "git_status"
inner_prefix = " "
inner_suffix = " "
outer_suffix = ""
background = "green"
foreground = "black"
padding = ""

[[module]]
name = "separator"
background = "default"
outer_suffix = ""

[[module]]
name = "execution_time"
inner_prefix = "⌛︎"
outer_suffix = ""
background = "yellow"
foreground = "black"

[[module]]
name = "separator"
background = "default"
outer_suffix = ""

[[module]]
name = "exit_status"
inner_prefix = "⚠ "
outer_suffix = ""
background = "red"
foreground = "black"
