[global]
padding = ""

[prompt]
string = " ‚ùØ "
foreground = "green"
error_foreground = "red"

[connector]
character = "‚îÄ"

[execution_time]
display_from = 2.0

[date]
format = "%F"

[time]
format = "%T"

[exit_status]
non_zero_only = true

[[module]]
name = "directory"
inner_prefix = "üñø  "
outer_prefix = " "
outer_suffix = " "
foreground = "blue"
bold = true

[[module]]
name = "git_branch"
inner_prefix = "ÓÇ† "
outer_suffix = " "
foreground = "green"

[[module]]
name = "git_status"
outer_suffix = " "
foreground = "green"

[[module]]
name = "execution_time"
inner_prefix = "‚åõÔ∏é"
outer_suffix = " "
foreground = "yellow"

[[module]]
name = "exit_status"
inner_prefix = "‚ö† "
outer_suffix = " "
foreground = "red"

[[module]]
name = "date"
align = "right"
padding = " "

[[module]]
name = "time"
align = "right_prompt"
outer_suffix = " "

[[module]]
name = "fixed"
position = 0
outer_prefix = "‚ï≠‚îÄ"

[[module]]
name = "fixed"
level = 2
outer_prefix = "‚ï∞‚îÄ"

[[module]]
name = "fixed"
align = "right"
outer_suffix = "‚îÄ‚ïÆ"

[[module]]
name = "fixed"
align = "right_prompt"
outer_suffix = "‚îÄ‚ïØ"
