[global]
padding = ""

[prompt]
string = " ❯ "
foreground = "green"
error_foreground = "red"

[execution_time]
display_from = 2.0

[exit_status]
non_zero_only = true

[[module]]
name = "directory"
foreground = "blue"
bold = true

[[module]]
name = "git_branch"
align = "right_prompt"
inner_prefix = " "
outer_prefix = " "
foreground = "green"

[[module]]
name = "git_status"
align = "right_prompt"
outer_prefix = " "
foreground = "green"

[[module]]
name = "execution_time"
align = "right_prompt"
inner_prefix = "⌛︎"
outer_prefix = " "
foreground = "yellow"

[[module]]
name = "exit_status"
align = "right_prompt"
inner_prefix = "⚠ "
outer_prefix = " "
foreground = "red"
