[global]
new_line = true
padding = " "

[prompt]
string = "\n‚ùØ "
foreground = "green"
error_foreground = "red"

[connector]
character = "‚îÄ"
foreground = ""
background = ""
dim = false

[directory]
basename_only = false

[execution_time]
precision = 1
display_from = 2.0
display_fractional_until = 10.0

[git_branch]
ignore = []

[git_status]
count = true
spacing = " "
clean = "‚úì"
ahead = "‚Üë"
behind = "‚Üì"
stashed = "$"
untracked = "?"
conflicted = "="
modified = "!"
staged = "+"
renamed = "¬ª"
deleted = "‚úò"

[date]
format = "%F"

[time]
format = "%T"

[exit_status]
non_zero_only = true

[[module]]
name = "directory"
align = "left"
inner_prefix = ""
inner_suffix = ""
outer_prefix = ""
outer_suffix = "ÓÇ∞"
background = "blue"
foreground = "black"
bold = false
dim = false
italic = false
underline = false

[[module]]
name = "separator"
align = "left"
background = "default"
outer_suffix = "ÓÇ∞"

[[module]]
name = "git_branch"
align = "left"
inner_prefix = " ÓÇ† "
inner_suffix = ""
outer_prefix = ""
outer_suffix = ""
background = "green"
foreground = "black"
bold = false
dim = false
italic = false
underline = false
padding = ""

[[module]]
name = "git_status"
align = "left"
inner_prefix = " "
inner_suffix = " "
outer_prefix = ""
outer_suffix = "ÓÇ∞"
background = "green"
foreground = "black"
bold = false
dim = false
italic = false
underline = false
padding = ""

[[module]]
name = "separator"
align = "left"
background = "default"
outer_suffix = "ÓÇ∞"

[[module]]
name = "execution_time"
align = "left"
inner_prefix = "‚åõÔ∏é"
inner_suffix = ""
outer_prefix = ""
outer_suffix = "ÓÇ∞"
background = "yellow"
foreground = "black"
bold = false
dim = false
italic = false
underline = false

[[module]]
name = "exit_status"
align = "left"
inner_prefix = "‚ö† "
inner_suffix = ""
outer_prefix = ""
outer_suffix = "ÓÇ∞"
background = "red"
foreground = "black"
bold = false
dim = false
italic = false
underline = false

[[module]]
name = "date"
align = "right"
inner_prefix = "üóì "
inner_suffix = ""
outer_prefix = "ÓÇ≤"
outer_suffix = ""
background = "magenta"
foreground = "black"
bold = false
dim = false
italic = false
underline = false

[[module]]
name = "separator"
align = "right"
background = "default"
outer_prefix = "ÓÇ≤"

[[module]]
name = "time"
align = "right"
inner_prefix = "‚è≤ "
inner_suffix = ""
outer_prefix = "ÓÇ≤"
outer_suffix = ""
background = "cyan"
foreground = "black"
bold = false
dim = false
italic = false
underline = false
