[global]
padding = " "

[prompt]
string = "\n❯ "
foreground = "#25c145"
error_foreground = "#e83030"
new_line = true
separator = "─"
transient = true

# [[module]]
# name = "user"
# outer_suffix = ""
# background = "#513559"
# foreground = "#ffffff"

[[module]]
name = "separator"
outer_suffix = ""
background = "default"

[[module]]
name = "directory"
inner_prefix = "  "
outer_suffix = ""
background = "#007aff"
foreground = "#ffffff"

[[module]]
name = "separator"
outer_suffix = ""
background = "default"

[[module]]
name = "git_branch"
inner_prefix = " "
background = "#25c145"
foreground = "#ffffff"

[[module]]
name = "git_commit"
inner_prefix = " "
background = "#25c145"
foreground = "#ffffff"

[[module]]
name = "git_status"
inner_suffix = " "
outer_suffix = ""
background = "#25c145"
foreground = "#ffffff"
padding = ""

[[module]]
name = "separator"
outer_suffix = ""
background = "default"

[[module]]
name = "duration"
inner_prefix = "⌛︎"
outer_suffix = ""
background = "#e38029"
foreground = "#ffffff"

[[module]]
name = "separator"
outer_suffix = ""
background = "default"

[[module]]
name = "status"
inner_prefix = "⚠ "
outer_suffix = ""
background = "#e83030"
foreground = "#ffffff"

[[module]]
name = "separator"
outer_suffix = ""
background = "default"

# [[module]]
# name = "time"
# inner_prefix = " "
# outer_suffix = ""
# background = "#868686"
# foreground = "#ffffff"
